[package]
name = "phf_codegen"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.7.20"
license = "MIT"
description = "Codegen library for PHF types"
repository = "https://github.com/sfackler/rust-phf"
documentation = "https://sfackler.github.io/rust-phf/doc/v0.7.20/phf_codegen"

[dependencies]
phf_generator = { version = "=0.7.20", path = "../phf_generator" }
phf_shared = { version = "=0.7.20", path = "../phf_shared" }
