[package]
name = "phf_codegen"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.7.23"
license = "MIT"
description = "Codegen library for PHF types"
repository = "https://github.com/sfackler/rust-phf"
documentation = "https://docs.rs/phf_codegen/0.7.23/phf_codegen"

[dependencies]
phf_generator = { version = "=0.7.23", path = "../phf_generator" }
phf_shared = { version = "=0.7.23", path = "../phf_shared" }
