language: rust
sudo: false
cache: cargo
rust:
- nightly
- beta
- 1.11.0
script:
- (test $TRAVIS_RUST_VERSION != "nightly" || (cd phf_macros && cargo test))
- (test $TRAVIS_RUST_VERSION != "nightly" || (cd phf_macros && cargo test --features unicase_support))
- (test $TRAVIS_RUST_VERSION != "nightly" || (cd phf_macros && cargo bench))
- (test $TRAVIS_RUST_VERSION != "nightly" || (cd phf_shared && cargo build --features core))
- (test $TRAVIS_RUST_VERSION != "nightly" || (cd phf && cargo build --features core))
- (cd phf_codegen && cargo test)
- (cd phf_codegen/test && cargo test)
