[package]
name = "phf_macros"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.7.23"
license = "MIT"
description = "Compiler plugin for perfect hash function data structures"
repository = "https://github.com/sfackler/rust-phf"
documentation = "https://docs.rs/phf_macros/0.7.23/phf_macros"

[lib]
name = "phf_macros"
path = "src/lib.rs"
plugin = true
test = false

[features]
unicase_support = ["unicase", "phf_shared/unicase"]

# Deprecated
stats = []

[dependencies]
phf_generator = { version = "=0.7.23", path = "../phf_generator" }
phf_shared = { version = "=0.7.23", path = "../phf_shared" }
unicase = { version = "1.4", optional = true }

[dev-dependencies]
compiletest_rs = "0.3"
phf = { version = "0.7.23", path = "../phf" }

