[package]
name = "phf_macros"
version = "0.7.23"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["full"] }
quote = "0.6"
proc-macro2 = "0.4"

phf_generator = { version = "=0.7.23", path = "../phf_generator" }
phf_shared = { version = "=0.7.23", path = "../phf_shared" }

[dev-dependencies]
compiletest_rs = "0.3"
phf = { version = "0.7.23", path = "../phf", features = ["macros"] }
