[package]
name = "phf_macros"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.7.16"
license = "MIT"
description = "Compiler plugin for perfect hash function data structures"
repository = "https://github.com/sfackler/rust-phf"
documentation = "https://sfackler.github.io/rust-phf/doc/v0.7.16/phf_macros"

[lib]
name = "phf_macros"
path = "src/lib.rs"
plugin = true
test = false

[features]
stats = ["time"]
unicase_support = ["unicase", "phf_shared/unicase"]

[dependencies.phf_generator]
path = "../phf_generator"
version = "=0.7.16"

[dependencies.phf_shared]
path = "../phf_shared"
version = "=0.7.16"

[dependencies.time]
version = "0.1"
optional = true

[dependencies.unicase]
version = "1.4"
optional = true

[dev-dependencies.phf]
path = "../phf"
version = "=0.7.16"
