[package]
name = "phf_generator"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.7.20"
license = "MIT"
description = "PHF generation logic"
repository = "https://github.com/sfackler/rust-phf"
documentation = "https://docs.rs/phf_generator/0.7.20/phf_generator"

[dependencies]
rand = "0.3"
phf_shared = { version = "=0.7.20", path = "../phf_shared" }
