[package]
name = "phf_builder"
version = "0.7.13"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "Runtime creation of perfect hash function data structures"
repository = "https://github.com/sfackler/rust-phf"
documentation = "https://sfackler.github.io/rust-phf/doc/v0.7.13/phf_builder"

[dependencies]
phf = { version = "=0.7.13", path = "../phf" }
phf_generator = { version = "=0.7.13", path = "../phf_generator" }
