[package]
name = "phf_builder"
version = "0.7.13"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[dependencies]
phf = { version = "=0.7.13", path = "../phf" }
phf_generator = { version = "=0.7.13", path = "../phf_generator" }
